### PR TITLE
feat: Add support for readiness\liveness probes

### LINKED ISSUE #42: Configure Readiness and Liveness Probes
This Helm Chart doesn't configure Readiness or Liveness Probes, which results in the Pods persisting in a broken state if something undesirable happens.

For extra context, I believe our specific situation was a Kubernetes cluster that scaled down out of hours but still needed Twingate access. DNS was accidentally broken in this cluster out of hours, but when the cluster scaled back up the Twingate connector never recovered (which is a separate issue than this) until the Pods were manually deleted/restarted.

```
[msg] All nameservers have failed
[msg] Nameserver 172.20.0.10:53 is back up
[msg] Nameserver 172.20.0.10:53 has failed: request timed out.
[msg] All nameservers have failed
```

This could/would/should have been fixed automatically by a Liveness Probe.

I noticed that there is documentation about [Connector Health Checks](https://www.twingate.com/docs/connector-health-checks) and so I think it's just a matter of adding a liveness probe that checks if this is returning `OK` or not.

Interestingly, this doesn't seem to solve *my* exact issue, as my pod which is showing as `Controller Could not connect` in the Twingate Console shows returns`OK` in the health check:

```
kubectl exec -ti -n cloud twingate-a-857875bfb7-s2x29 -- /connectorctl health
OK
```

### PR DESCRIPTION
**Pull request by ekampf**
#### What this PR does / why we need it:

Resolves #42 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by twingate-blee — APPROVED** [review]
lgtm

**Comment by loganbest** [comment]
I can confirm in the related issue the statement:
> Interestingly, this doesn't seem to solve my exact issue, as my pod which is showing as Controller Could not connect in the Twingate Console shows returnsOK in the health check:

This also happens to me. When there's a problem with external-dns in k8s for whatever reason (currently self inflicted, but not important) the pod spits out the same logs as in the #42 issue. When I check the `/connectorctl health` command it still says it's `OK` but Twingate stlil says it's offline, until I kill the pod and let it reschedule. 

readiness/liveliness probes are essential, but there's a bigger root problem to fix as to why the health check is returning OK when it's clearly not OK.

**Comment by ekampf** [comment]
@loganbest the way healthcheck is implemented today - it just checks that the connector process is up and functioning not that the connector is connected or not.
Reason is, if connector is not connected its either deployed with invalid tokens or there's some external reason preventing it from connecting (network policy forbidding egress, firewall, ...)

Failing liveness and restarting the pod wont help fixing any of these issues - we'll just have a pod that keeps restarting (and potentially, in the invalid token case, spamming twingate with invalid connection requests)

**Comment by loganbest** [comment]
> @loganbest the way healthcheck is implemented today - it just checks that the connector process is up and functioning not that the connector is connected or not.
> 
> Reason is, if connector is not connected its either deployed with invalid tokens or there's some external reason preventing it from connecting (network policy forbidding egress, firewall, ...)
> 
> 
> 
> Failing liveness and restarting the pod wont help fixing any of these issues - we'll just have a pod that keeps restarting (and potentially, in the invalid token case, spamming twingate with invalid connection requests)
> 
> 

Ok sure but if the connector doesn't actually reconnect when there's a network/dns failure then that seems like a pretty big bug that needs to be fixed. Otherwise what's the point of the health check if the connector isn't actually healthy? Healthy meaning up and functioning and connected. Health check should be able to ignore token issues as being a health problem and treat not being able to connect to twingate as a real health problem. Sure restarting the pod may not help here but in the absence of the connector retrying its connection to the twingate network it's better than just silently dying and staying that way. At least you'll get metrics on excessive pod restarts from k8s events and can see why from logs. 

The last thing anyone wants is to have an unexpected network/dns blip (which happens) and the vpn not even being able to reconnect on its own because it just gives up and doesn't restart.

**Comment by ekampf** [comment]
@loganbest you're right. Connector should recover on network\dns blip and it does for the most part.
Its hard to know what exactly was the issue here that made it not recover (might not even be a connector issue but a k8s one) without seeing logs but we are trying to reproduce on our end.

**Comment by loganbest** [comment]
> @loganbest you're right. Connector should recover on network\dns blip and it does for the most part. Its hard to know what exactly was the issue here that made it not recover (might not even be a connector issue but a k8s one) without seeing logs but we are trying to reproduce on our end.
> 
> Maybe the test we need to add to `./connectorctl health` is not wether connector is connected or not but wether `twingate.com` DNS resolves...

I've had a support ticket open since June 10 with logs. Ticket ID #11093

**Comment by ekampf** [comment]
Hey @loganbest 
  I checked the said ticket and the logs snippet there doesnt provide much context - we see nameserver is down but not clear when it becomes available again.

We did try to reproduce on our own kubernetes cluster by scaling all the DNS pods to zero and seeing connector go into Error mode.
As seen as I scale the DNS pods back up connector recovers:
```
[INFO] [connector] State: Error
[DEBUG] [libsdwan] [controller] run_state_machine: Error
[msg] Nameserver 10.112.16.10:53 is back up
State: Offline
State: Authentication
[DEBUG] [libsdwan] [controller] set_state: switching from "Error" to "Restart"
.```

Just so we dont have multiple threads I suggest we move this discussion back to Zendesk. If there is an issue to fix here its not related to the helm chart so lets figure it out there with our Support team.

Thanks,
Eran

**Pull request merged**
