### PR TITLE
Better support for namespaces

### LINKED ISSUE #19: Add namespace "Release.Namespace"
Hi,

Is it possible to add the metadata `namespace: {{ .Release.Namespace }}` in all the resources?

We are deploying using Skaffold/Cloud Deploy, and it cannot deploy to a specific namespace without it. It is a quite standard way to define the namespace in Helm charts.

Thanks!

### PR DESCRIPTION
**Pull request by chenbishop**
#### Which issue this PR fixes if any
Resolves #19 

#### Special notes for your reviewer:
- Adds {{ .Release.Namespace }} to deployment and secret

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by twingate-blee — APPROVED** [review]
lgtm

**Review by romankor — CHANGES_REQUESTED** [review]
https://github.com/Twingate/helm-charts/issues/19#issuecomment-1468447759

**Review by chenbishop — COMMENTED** [review]
please review and approve

**Review by romankor — APPROVED** [review]
GTM

**Comment by ekampf** [comment]
@chenbishop I'm closing this PR per @romankor 's comment and [this](https://github.com/helm/helm/issues/5465#issuecomment-473942223) clarification from the helm team on a similar issue

**Comment by ekampf** [comment]
After more discussions we decided to support this as its not breaking existing helm `--namespace` behavior.
However I want to merge the unit tests PR #22 first and add unit tests here

**Pull request closed without merging**
