### PR TITLE
Added imagePullSecrets to helm chart

### PR DESCRIPTION
**Pull request by ykizin**
Hello!
@ekampf please, review my PR

**What this PR does / why we need it:**
We found that there was no variable in the chart to specify the Docker Secret, which caused the connector to be unavailable when it tried to restart (it was specified in the README, but there was no functionality).

I would be grateful if you could consider my changes. 

**Checklist:**
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by ekampf — APPROVED** [review]

**Comment by ekampf** [comment]
Thanks @ykizin !

**Comment by ekampf** [comment]
@ykizin unfortunately I had to revert this after merging - it breaks all the tests adding some weird whitespaces after (`spec:`)
Can you fix and reopen?  (run tests by running `go test -v ./...`)

**Comment by ykizin** [comment]
@ekampf oh, sorry. Of cause! I forgot them, only installed on dev cluster for tests

**Comment by ekampf** [comment]
@ykizin no worries created a new PR with fix.

**Comment by ekampf** [comment]
@ykizin see https://github.com/Twingate/helm-charts/pull/51
for some reason couldnt get it to work with a helper template.
Since this is a non-reusable block thats only needed in the deployment yaml no reason to have it as a helper anyway

**Comment by ykizin** [comment]
@ekampf 

That makes sense, thanks for fixing my PR

**Pull request merged**
